# Site settings
title: Victor Zohni
email: victorzohni@gmail.com
url: https://example.github.io
description: "A website for programmer Victor Zohni!"
keywords: "Hip, Fresh, Cool, Art, Tech"
skills: "Creative Developer"
meta_author: Zohni Victor
baseurl: /website3

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00b3fe #80B3FF
  primary-rgb: "0,179,254" #"128,179,255"
  secondary: 384452 #FD6E8A
  secondary-dark: 233140 #A2122F

#primary: 18bc9c #80B3FF  primary-rgb: "24,288,156" #"128,179,255" secondary: 2c3e50 #FD6E8A   secondary-dark: 233140 #A2122F


# Footer settings
footer:
  copyright: Victor Zohni
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/victor-zohni-b443a1a8/  
  - title: github
    url: https://github.com/vzohni

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Email: victorzohni@gmail.com'

# Build settings
markdown: kramdown
permalink: pretty
